# Generated by Django 3.0.1 on 2020-02-04 12:01

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.CharField(default=employee.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.CharField(default=employee.models.uuid_str, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contract_employee', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
